# Generated by Django 4.2.2 on 2023-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email_address",
            field=models.EmailField(default="hhhdsfha@chikna.com", max_length=254),
        ),
    ]
