# Generated by Django 4.2.2 on 2023-07-23 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField(default=0)),
                ("total_income", models.FloatField(default=0)),
                ("total_withdrawn", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binary_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "transaction_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        length=16,
                        max_length=20,
                        prefix="Xe",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        max_length=10,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("transaction_time", models.DateTimeField(auto_now=True)),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("step", "Step"),
                            ("binary", "Binary"),
                            ("gift_reward", "Gift_Reward"),
                            ("account", "Account"),
                            ("nil", "Nil"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_log",
                        to="binary_plan.binarywallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinaryUserInstence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direct_income", models.FloatField(default=0)),
                ("step_income", models.FloatField(default=0)),
                ("binary_income", models.FloatField(default=0)),
                ("gift_and_rewards", models.FloatField(default=0)),
                ("business_volume", models.FloatField(default=0)),
                ("live", models.BooleanField(default=True)),
                ("stage1", models.BooleanField(default=False)),
                ("stage2", models.BooleanField(default=False)),
                ("stage3", models.BooleanField(default=False)),
                ("stage4", models.BooleanField(default=False)),
                ("number_of_referrals", models.IntegerField(default=0)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "left_leg",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_legs",
                        to="binary_plan.binaryuserinstence",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="binary_plan.binaryuserinstence",
                    ),
                ),
                (
                    "refferal",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refferals",
                        to="binary_plan.binaryuserinstence",
                    ),
                ),
                (
                    "right_leg",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_legs",
                        to="binary_plan.binaryuserinstence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_instance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BinaryTreeQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_instance",
                        to="binary_plan.binaryuserinstence",
                    ),
                ),
            ],
        ),
    ]
