name: Broken Links Checker
on:
  schedule:
    - cron:  '0 1 1 * *'
  workflow_dispatch:

env:
  WEBSITE_URL: "https://academicpages.github.io/"
  ISSUE_TEMPLATE: ".github/ISSUE_TEMPLATE/check-broken-links.md"
  
jobs:
  checking_for_broken_links:
    runs-on: ubuntu-latest
    timeout-minutes: 5 

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      if: ${{ failure() }}
    - uses: JasonEtco/create-an-issue@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
  
