name: Broken Links Checker
on:
  schedule:
    - cron:  '0 1 1 * *'
  workflow_dispatch:

env:
  WEBSITE_URL: "https://open-horizon.github.io/"
  ISSUE_TEMPLATE: ".github/ISSUE_TEMPLATE/check-broken-links.md"
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive
  
  create_issue:
    runs-on: ubuntu-latest
    
    timeout-minutes: 5    
    steps:
    - uses: actions/checkout@v2
      if: failure()

    - uses: JasonEtco/create-an-issue@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
