name: Link Snitch

on:
  schedule:
    - cron:  '0 1 1 * *'
  workflow_dispatch:
  
 
env:
  URL: https://open-horizon.github.io/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
